### ISSUE TITLE
Crear modelo de Menú

### ISSUE THREAD

**Issue by rubsuadav** [TFG-nicsanmen-rubsuadav/backend#15]
Parent with #3

**Comment by nicsanmen** [comment]
El modelo menú contará con la siguiente info:

Primero tener en cuenta que un restaurante puede tener más de 1 menú o carta, es decir, es una FK, no una o2o.
Un menú estará compuesto de secciones (entrantes, bebidas, carnes...) éstas las crea el propietario.
Cada sección tiene un número de platos (1...*), estos platos a su vez pueden tener categorías: acotaremos a tapa, media y entera, que se pueda seleccionar la que quiera o ninguna y que solo hay una opción. Y su respectivo precio (por categoría o si no hay categorías, precio único por plato, que será el caso de las bebidas por ejemplo).

Los atributos de cada colección serán:
Menu: nombre, descripción, disponible, *secciones*
Sección: nombre, descripción, disponible, *platos*
Plato: nombre, descripción, disponible, *categoría* (opcional, con nombre y precio), precio (en caso de no tener categorías), *alérgenos*
Categoría: nombre, precio
Alérgenos: los 14 alérgenos, será como un enum.
