### ISSUE TITLE
Web scrapping

### ISSUE THREAD

**Issue by nicsanmen** [TFG-nicsanmen-rubsuadav/backend#5]
Se realizará el web scrapping de la [página ](https://gastroranking.es/restaurantes/). Junto a este scrapping utilizando beautifulsoup4 se recuperarán los siguientes datos:

- Nombre
- Puntuación global y por plataforma
- Dirección
- Teléfono
- Web
- Opiniones

Es recomendable realizar antes la issue #4 para poder almacenar los datos

**Comment by nicsanmen** [comment]
También vamos a guardar algunas variables como:
- Tipo de servicio (restaurante, take-away, reparto a domicilio)
- Rango de precio
- Imagen

cc: @rubsuadav

**Comment by rubsuadav** [comment]
Se ha realizado el web scrapping completo de los atributos paralelizándolo completamente
